### PR TITLE
Get all widget parent ids on click

### PR DESCRIPTION
**Pull request by ChrisJefferson**
There is probably a much better way of doing this (and it might already be in the library), but I thought I would upload a PR for discussion.

I was finding the "targetId" less useful than I hoped, as it is often empty, unless I give an Id to every single element. In practice I usually want the first named parent which has an Id, so I added a quick function to get that.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Random thought -- I wonder for future-proofing if it would be worth returning a list of all non-null IDs, back to the root? It would be more data to pass back, but shouldn't be that much data (except for very deeply nested svgs with lots of IDs).

**Comment by cduck** [comment]
Thanks @ChrisJefferson for the PR.  This looks reasonable to me but I wonder if it's browser-dependent.  I mostly develop on Firefox.  What did you try it on?

I'm slightly worried this will lead to brittle code in some cases because drawsvg automatically adds ids as needed by things like `Use`.  Your second suggestion might work better.

I'd be happy to merge this or your second suggestion.  Let me know your thoughts.

**Comment by ChrisJefferson** [comment]
Hi,

I've updated to now return all ids up to the parent root. I tested this works on chrome+firefox, and also in vscode's juypter notebook support.

This code should work everywhere, it's (assuming I haven't done anything stupid) fairly standard event handling code.

I include a demo below -- it's probably too long to be in the readme, I wanted to make it a decent length to make a few different groups with different ids. We can see from this that we can identify which group is clicked on, and also the group that group is contained in (and as the ids come as a list, it's easy to filter / check order, if one wishes).

I am already using this in my code (I'm making simple clickable puzzles, like Sudoku. Once it's a bit more polished I'll share a link), this seems to let me get what is clicked on fairly well.

**Comment by ChrisJefferson** [comment]
```
import drawsvg as draw
from drawsvg.widgets import DrawingWidget

# Create drawing
d = draw.Drawing(4,4, origin='center', context=draw.Context(invert_y=True))
d.set_render_size(500)
c = {'g1': 0, 'g2': 0, 'g3': 0, 'text': 0}
group1 = draw.Group(id="g1")
d.append(group1)
group1.append(draw.Circle(0, 0, 1, fill='orange'))
group2 = draw.Group(id="g2")
group2.append(draw.Circle(0, 1, 1, fill='red'))
group1.append(group2)
group3 = draw.Group(id="g3")
group3.append(draw.Circle(1, 0, 1, fill='blue'))
d.append(group3)

text = draw.Group(id="text")
d.append(text)

def redraw():
    text.children.clear()
    string = f"Orange+Red: {c['g1']}, Red: {c['g2']}\nBlue: {c['g3']}, Text: {c['text']}"
    text.append(draw.Text(string, 0.2, -1, 1.8))
redraw()

# Create interactive widget and register mouse events
widget = DrawingWidget(d)
@widget.mousedown
def mousedown(widget, x, y, info):
    for id in info['targetParentIds']:
        c[id] += 1
    redraw()
    widget.refresh()
widget
```

**Comment by cduck** [comment]
Great.  I've been busy but I will merge and publish a new version as soon as I have some time.

I appreciate how active you've been! Would you be interested in creating a short documentation page that could be linked from the readme or the compiled documentation (as a separate PR)?  Any additional documentation you create while making your game would be helpful to other users.

**Comment by cduck** [comment]
Merged.  This feature is included in the new package [version 2.2.0](https://pypi.org/project/drawsvg/2.2.0/).

**Pull request merged**
