### PR TITLE
Add FrameAnimationContext for Spritesheets

### PR DESCRIPTION
**Pull request by TheMightyComp**
Hi,

I wanted to use drawsvg to programmatically create some art assets for a game I'm working on, so I added a feature to render a `FrameAnimation` as a bitmap spritesheet (i.e. a single raster image with each frame laid out in a grid). The new function `frame_animate_spritesheet` works just like `frame_animate_video`, and takes an optional `row_length` parameter to determine the dimensions of the spritesheet.

If this feature is outside the scope of the project, feel free to pass on it - I just thought I'd submit the code if you find it worth including.

Example usage:
```python
import drawsvg as draw

def draw_frame(t):
    d = draw.Drawing(2, 6.05, origin=(-1, -5))
    d.set_render_size(h=300)
    t = (t + 1) % 2 - 1
    y = t**2 * 4 - 4
    d.append(draw.Circle(0, y, 1, fill='lime'))
    return d

with draw.frame_animate_spritesheet('example.png', draw_frame, row_length=10) as anim:
    for i in range(20):
        anim.draw_frame(i/10)
    for i in range(20):
        anim.draw_frame(i/10)
    for i in range(20):
        anim.draw_frame(i/10)
```

### CODE REVIEW

**Comment by cduck** [comment]
Cool!  This is a nice use of the frame animation context.  I will definitely merge it once I have some time to look more closely at the code.

Is this grid-based sprite-sheet layout standard or common?  Do you have example code to import the PNG into a game engine?

**Comment by TheMightyComp** [comment]
Thanks - I'm happy to make any changes necessary. 

Sprite sheets like this are built into most 2D game engines - here are some examples from the docs of [Godot](https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html#sprite-sheet-with-animatedsprite2d) and [Phaser.js](https://newdocs.phaser.io/docs/3.54.0/focus/Phaser.Loader.LoaderPlugin-spritesheet).

**Comment by cduck** [comment]
After merging this, I also added support for spritesheet output from native animations (via `Drawing.as_spritesheet()`).  I appreciate the clean code that made this easy.

Published version [2.1.0](https://pypi.org/project/drawsvg/2.1.0/).

**Comment by TheMightyComp** [comment]
Thanks, glad it was easy to extend!

**Pull request merged**
